document.addEventListener('click',e=>{if(e.target.classList.contains('empty-demo')){data.length?clearFilters():$('demo').click()}if(scanActive&&!e.target.closest('input,select,textarea,button,.modalbox'))setTimeout(()=>els.scanner.focus(),0)})
function updateField(target){const id=Number(target.dataset.id),x=byId.get(id);if(!x)return;let field;if(target.classList.contains('first'))field='firstQty';else if(target.classList.contains('review'))field='reviewQty';else field='reason';const old=x[field],nv=target.value;if(old===nv)return;x[field]=nv;logChange(x,field,old,nv,field==='firstQty'?'初盘数量':field==='reviewQty'?'复盘数量':'差异原因');render();scheduleSave()}
function attachInput(container){container.addEventListener('change',e=>{if(e.target.matches('.q,.reason'))updateField(e.target)});container.addEventListener('focusin',e=>{if(e.target.classList.contains('reason')&&activeReason&&!e.target.value)e.target.value=activeReason;if(e.target.classList.contains('q')&&window.innerWidth<=760){setTimeout(()=>e.target.closest('.mcard,tr')?.scrollIntoView({behavior:'smooth',block:'center'}),320)}})}
attachInput(els.tbody);attachInput(els.cards);
function scanSound(ok){try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=ok?880:220;g.gain.value=.06;o.connect(g);g.connect(c.destination);o.start();setTimeout(()=>{o.stop();c.close()},ok?80:220)}catch{}}
function applyScanToItem(x){const st=num($('scanStep').value);if(!st.ok||st.v<=0){setScan('扫码变化数量必须大于 0','err');flashScanner(false);return}const dir=Number($('scanDirection').dataset.dir||1),f=$('round').value==='review'?'reviewQty':'firstQty',cur=num(x[f]),old=x[f];let next=round((cur.ok?cur.v:0)+dir*st.v);if(next<0){next=0;setScan('数量不能低于 0，已调整为 0。','warn')}const nv=String(next);x[f]=nv;logChange(x,f,old,nv,f==='reviewQty'?'复盘数量':'初盘数量');render();scheduleSave();setScan(`${x.name}｜${dir>0?'增加':'减少'} ${st.v}｜当前 ${nv}`,'ok');flashScanner(true);scanSound(true);setTimeout(()=>{document.querySelector(`tr[data-id="${x.id}"]`)?.scrollIntoView({block:'center'});if(scanActive)els.scanner.focus()},30)}
function handleScan(raw){const c=codeNorm(raw);els.scanner.value='';if(!c){if(scanActive)els.scanner.focus();return}const m=byCode.get(c);if(!m||!m.length){setScan('未找到商品：'+c,'err');flashScanner(false);scanSound(false);if(navigator.vibrate)navigator.vibrate(120);setTimeout(()=>{els.scanner.value='';if(scanActive)els.scanner.focus()},50);return}if($('scanMode').value==='locate'){state.keyword=c;$('search').value=c;render();setScan(`已定位：${m.length} 条记录`,'ok');flashScanner(true);setTimeout(()=>{document.querySelector(`[data-id="${m[0].id}"] .${$('round').value==='review'?'review':'first'}`)?.focus()},50);return}if(m.length>1){pendingDupScan={items:m};$('dupChoices').innerHTML=m.map(x=>`<button class="outline dup-choice" data-id="${x.id}" style="width:100%;text-align:left;margin:5px 0">${esc(x.name)}｜库位 ${esc(x.location||'-')}｜批次 ${esc(x.batch||'-')}</button>`).join('');$('dupModal').classList.remove('hide');setScan(`编码 ${c} 对应多条记录，请选择库位或批次。`,'warn');return}applyScanToItem(m[0])}
$('dupChoices').onclick=e=>{if(!e.target.classList.contains('dup-choice'))return;const x=byId.get(Number(e.target.dataset.id));$('dupModal').classList.add('hide');if(x)applyScanToItem(x)}
$('closeDup').onclick=()=>{$('dupModal').classList.add('hide');if(scanActive)els.scanner.focus()}
$('scanner').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();handleScan(e.target.value);requestAnimationFrame(()=>{if(scanActive)e.target.focus()})}})
$('focusScan').onclick=()=>{scanActive=!scanActive;$('focusScan').textContent=scanActive?'结束持续扫码':'开始持续扫码';els.scanner.classList.toggle('scan-active',scanActive);if(scanActive){els.scanner.focus();setScan('持续扫码已开启。扫码后会自动清空并继续等待下一次扫描。','ok')}else setScan('持续扫码已关闭。')}
$('scanDirection').onclick=()=>{const b=$('scanDirection'),next=Number(b.dataset.dir)===1?-1:1;b.dataset.dir=String(next);b.textContent=next===1?'＋累加':'－纠错';b.className=next===1?'success':'warning';if(scanActive)els.scanner.focus()}
$('search').oninput=e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.keyword=e.target.value.trim();render()},160)}
$('filter').onchange=e=>{state.filter=e.target.value;render();setStatus(`当前过滤下匹配 ${list().length} 条。`)}
$('moreFilter').onchange=e=>{state.moreFilter=e.target.value;render()}
$('sort').onchange=e=>{state.sort=e.target.value;render()}
$('round').onchange=e=>{state.round=e.target.value}
$('operator').onchange=e=>{state.operator=e.target.value;scheduleSave()}
$('warehouse').onchange=e=>{state.warehouse=e.target.value;scheduleSave()}
$('clearSearch').onclick=clearFilters
$('reasonBar').innerHTML=reasons.map(r=>`<span class="reason-group"><button class="reason-pick" data-reason="${r}">${r}</button><button class="reason-apply" data-reason="${r}" title="批量应用到当前筛选中的空白差异项">批量</button></span>`).join('')
$('reasonBar').onclick=e=>{const r=e.target.dataset.reason;if(!r)return;if(e.target.classList.contains('reason-pick')){activeReason=r;document.querySelectorAll('.reason-pick').forEach(x=>x.classList.toggle('active',x.dataset.reason===r));return}const targets=baseList().filter(x=>{const d=diff(x);return d.entered&&d.valid&&d.dq!==0&&!x.reason});if(!targets.length){alert('当前筛选结果中没有“有差异且原因空”的商品。');return}if(!confirm(`将“${r}”应用到当前筛选中的 ${targets.length} 条空白差异项？`))return;const changes=[];targets.forEach(x=>{changes.push({id:x.id,field:'reason',oldVal:x.reason,newVal:r});x.reason=r});logBatch(changes,`批量填写差异原因：${r}`);render();scheduleSave()}
$('batchConfirm').onclick=()=>{const field=$('round').value==='review'?'reviewQty':'firstQty',targets=baseList().filter(x=>x[field]==='');if(!targets.length){alert('当前筛选结果中没有可批量确认的空白数量。');return}if(!confirm(`将当前筛选结果中的 ${targets.length} 条空白${field==='reviewQty'?'复盘':'初盘'}数量设为系统数量？已有数量不会覆盖。`))return;const changes=[];targets.forEach(x=>{const nv=String(x.sysQty);changes.push({id:x.id,field,oldVal:x[field],newVal:nv});x[field]=nv});logBatch(changes,'批量确认无差异');render();scheduleSave()}
$('undo').onclick=()=>{const a=actions.pop();if(!a)return;if(a.type==='single'){const x=byId.get(a.id);if(x)x[a.field]=a.oldVal}else if(a.type==='batch'){a.changes.forEach(c=>{const x=byId.get(c.id);if(x)x[c.field]=c.oldVal})}logs.unshift({time:now(),code:'撤销',name:'撤销上一步操作',field:'',oldVal:'',newVal:''});$('undo').disabled=!actions.length;render();scheduleSave()}
$('historyBtn').onclick=()=>{$('historyList').innerHTML=logs.length?logs.map(l=>`<div class="logitem"><b>${esc(l.time)}</b>｜${esc(l.code)} ${esc(l.name)}｜${esc(l.field)} ${l.oldVal!==''||l.newVal!==''?`${esc(l.oldVal)} → ${esc(l.newVal)}`:''}</div>`).join(''):'暂无记录';$('historyModal').classList.remove('hide')}
$('closeHistory').onclick=()=>$('historyModal').classList.add('hide')
$('moreBtn').onclick=e=>{e.stopPropagation();$('moreMenu').classList.toggle('hide')}
document.addEventListener('click',e=>{if(!e.target.closest('.more'))$('moreMenu').classList.add('hide')})
$('pasteCodesBtn').onclick=()=>{$('pasteCodes').value='';$('pasteResult').textContent='';$('pasteModal').classList.remove('hide')}
$('closePaste').onclick=()=>$('pasteModal').classList.add('hide')
$('applyPaste').onclick=()=>{const codes=$('pasteCodes').value.split(/[\r\n\t,，;；]+/).map(codeNorm).filter(Boolean),unique=[...new Set(codes)],matched=new Set(),missing=[];unique.forEach(c=>byCode.has(c)?matched.add(c):missing.push(c));pasteCodeSet=matched;$('pasteResult').textContent=`输入 ${codes.length} 个，去重后 ${unique.length} 个，匹配 ${matched.size} 个，未匹配 ${missing.length} 个${missing.length?'：'+missing.slice(0,20).join('、'):''}`;state.keyword='';$('search').value='';render();setTimeout(()=>$('pasteModal').classList.add('hide'),450)}
function options(sel,hs,guess,optional=false){sel.innerHTML=(optional?'<option value="">不导入</option>':'')+hs.map(h=>`<option value="${esc(h)}">${esc(h)}</option>`).join('');const g=hs.find(h=>guess.some(k=>norm(h)===norm(k)))||hs.find(h=>guess.some(k=>norm(h).includes(norm(k))));if(g)sel.value=g}
function previewRows(rows){const p=rows.slice(0,5),hs=Object.keys(p[0]||{});$('preview').innerHTML=`<table><thead><tr>${hs.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${p.map(r=>`<tr>${hs.map(h=>`<td>${esc(r[h])}</td>`).join('')}</tr>`).join('')}</tbody></table><div class="status">预览前 ${p.length} 行，共 ${rows.length} 行。</div>`}
function loadSheet(name){const ws=workbook.Sheets[name];importRows=XLSX.utils.sheet_to_json(ws,{defval:'',raw:false});headers=Object.keys(importRows[0]||{});options($('mapCode'),headers,['商品编码','物料编码','SKU','货号','编码','code']);options($('mapName'),headers,['商品名称','物料名称','品名','名称','name']);options($('mapQty'),headers,['系统数量','系统库存','库存数量','账面数量','账面库存','qty','quantity']);options($('mapPrice'),headers,['单价','成本价','价格','price'],true);options($('mapLoc'),headers,['库位','仓位','货位','location'],true);options($('mapBatch'),headers,['批次','批号','batch'],true);options($('mapUnit'),headers,['单位','计量单位','unit'],true);previewRows(importRows)}
$('sheetSel').onchange=e=>loadSheet(e.target.value)
els.file.onchange=async e=>{const f=e.target.files[0];if(!f)return;if(typeof XLSX==='undefined'){alert('Excel 组件加载失败，请检查网络。');return}try{workbook=XLSX.read(await f.arrayBuffer(),{type:'array'});$('sheetSel').innerHTML=workbook.SheetNames.map(n=>`<option>${esc(n)}</option>`).join('');state.fileName=f.name;loadSheet(workbook.SheetNames[0]);$('importModal').classList.remove('hide')}catch(err){console.error(err);alert('读取文件失败')}finally{e.target.value=''}}
$('cancelImport').onclick=()=>$('importModal').classList.add('hide')
$('confirmImport').onclick=()=>{const k={c:$('mapCode').value,n:$('mapName').value,q:$('mapQty').value,p:$('mapPrice').value,l:$('mapLoc').value,b:$('mapBatch').value,u:$('mapUnit').value};if(!k.c||!k.n||!k.q){alert('必须映射商品编码、商品名称、系统数量');return}let arr=[],bad=[],seen=new Map();for(let i=0;i<importRows.length;i++){const r=importRows[i],qr=num(r[k.q]);if(!qr.ok||qr.v<0)bad.push(i+2);const x={id:i,code:String(r[k.c]??'').trim(),name:String(r[k.n]??'').trim(),location:k.l?String(r[k.l]??'').trim():'',batch:k.b?String(r[k.b]??'').trim():'',unit:k.u?String(r[k.u]??'').trim():'',sysQty:qr.ok&&qr.v>=0?qr.v:0,price:k.p?(num(r[k.p]).ok?Math.max(0,num(r[k.p]).v):0):0,firstQty:'',reviewQty:'',reason:'',updatedAt:''};if(!x.code&&!x.name)continue;const c=codeNorm(x.code);if(c&&seen.has(c)){const mode=$('dupMode').value;if(mode==='block'){alert('发现重复商品编码：'+c+'。请更换处理方式或修复源文件。');return}if(mode==='merge'){seen.get(c).sysQty=round(seen.get(c).sysQty+x.sysQty);continue}}arr.push(x);if(c)seen.set(c,x)}data=arr.map((x,i)=>({...x,id:i}));state.hasPrice=!!k.p;logs=[];actions=[];pasteCodeSet=null;rebuild();enable(true);$('operator').value=state.operator;$('warehouse').value=state.warehouse;$('importModal').classList.add('hide');render();saveAll();setStatus(`已导入 ${data.length} 条商品${bad.length?`；${bad.length} 行系统数量无效，已按 0 处理`:''}`,'ok')}
$('demo').onclick=()=>{data=[['6901001','矿泉水550ml','A-01','202607','瓶',120,1.5],['6901002','方便面红烧牛肉','A-02','202608','桶',80,4.2],['6901003','抽纸3层','B-01','','提',45,12.8],['6901004','洗衣液2kg','B-02','','瓶',30,29.9]].map((r,i)=>({id:i,code:r[0],name:r[1],location:r[2],batch:r[3],unit:r[4],sysQty:r[5],price:r[6],firstQty:'',reviewQty:'',reason:'',updatedAt:''}));state.hasPrice=true;state.fileName='演示数据';rebuild();enable(true);render();saveAll();setStatus('已加载演示数据。','ok')}
function reportRows(mode='all'){return data.filter(x=>{const d=diff(x);return mode==='all'||(mode==='diff'&&d.entered&&d.valid&&d.dq!==0)||(mode==='plus'&&d.dq>0)||(mode==='minus'&&d.dq<0)||(mode==='todo'&&!d.entered)}).map(x=>{const d=diff(x);return{'商品编码':x.code,'商品名称':x.name,'库位':x.location,'批次':x.batch,'单位':x.unit,'系统数量':x.sysQty,'初盘数量':x.firstQty===''?'':Number(x.firstQty),'复盘数量':x.reviewQty===''?'':Number(x.reviewQty),'最终数量':d.entered&&d.valid?d.final:'','差异数量':d.entered&&d.valid?d.dq:'','单价':state.hasPrice?x.price:'','差异金额':state.hasPrice&&d.entered&&d.valid?d.da:'','差异原因':x.reason}})}
function addSheet(wb,name,rows){const ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=[{wch:15},{wch:25},{wch:10},{wch:12},{wch:8},{wch:11},{wch:11},{wch:11},{wch:11},{wch:11},{wch:11},{wch:13},{wch:20}];ws['!autofilter']={ref:ws['!ref']};XLSX.utils.book_append_sheet(wb,ws,name)}
function exportBook(diffOnly){if(!data.length)return;const wb=XLSX.utils.book_new();if(diffOnly)addSheet(wb,'差异商品',reportRows('diff'));else{addSheet(wb,'全部商品',reportRows('all'));addSheet(wb,'差异商品',reportRows('diff'));addSheet(wb,'盘盈商品',reportRows('plus'));addSheet(wb,'盘亏商品',reportRows('minus'));addSheet(wb,'未盘商品',reportRows('todo'));addSheet(wb,'盘点汇总',[{'仓库名称':state.warehouse,'盘点人员':state.operator,'源文件':state.fileName,'导出时间':now(),'总商品':data.length,'已盘':data.filter(x=>diff(x).entered).length,'差异商品':data.filter(x=>diff(x).entered&&diff(x).dq!==0).length}])}const stamp=new Date().toISOString().replace(/[-:T]/g,'').slice(0,15),parts=[safeName(state.warehouse),safeName(state.operator),diffOnly?'盘点差异报告':'完整盘点报告',stamp].filter(Boolean);XLSX.writeFile(wb,parts.join('_')+'.xlsx')}
$('exportDiff').onclick=()=>exportBook(true);$('exportAll').onclick=()=>exportBook(false)
$('printBtn').onclick=()=>{$('pWarehouse').textContent=state.warehouse||'未填写';$('pOperator').textContent=state.operator||'未填写';$('pDate').textContent=new Date().toLocaleDateString('zh-CN');$('pFile').textContent=state.fileName||'未填写';printMode=true;render();setTimeout(()=>{window.print();printMode=false;render()},50)}
$('backup').onclick=()=>{const blob=new Blob([JSON.stringify({version:4,data,state,logs},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`盘点进度备份_${new Date().toLocaleDateString('sv-SE')}.json`;a.click();URL.revokeObjectURL(a.href)}
els.restore.onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const p=JSON.parse(await f.text());if(!Array.isArray(p.data))throw new Error();data=p.data;state={...state,...p.state};logs=Array.isArray(p.logs)?p.logs:[];rebuild();enable(true);$('search').value=state.keyword||'';$('filter').value=state.filter||'all';$('moreFilter').value=state.moreFilter||'';$('sort').value=state.sort||'index';$('operator').value=state.operator||'';$('warehouse').value=state.warehouse||'';render();saveAll();setStatus('已恢复进度备份。','ok')}catch{alert('备份文件无效或已损坏')}finally{e.target.value=''}}
$('clear').onclick=async()=>{if(!confirm('确定清空当前盘点？此操作会删除当前设备中的自动保存数据。'))return;data=[];byId.clear();byCode.clear();logs=[];actions=[];pasteCodeSet=null;await dbDel();enable(false);render();setStatus('当前盘点已清空。');setSave('','未保存')}
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='f'){e.preventDefault();$('search').focus()}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();saveAll()}if(e.key==='Escape'&&document.activeElement===$('search'))clearFilters();if(e.key==='Enter'&&document.activeElement?.classList.contains('q')){const inputs=[...document.querySelectorAll('.q')],i=inputs.indexOf(document.activeElement);if(i>=0&&inputs[i+1]){e.preventDefault();inputs[i+1].focus();inputs[i+1].select()}}})
(async()=>{try{const p=await dbGet();if(p&&Array.isArray(p.data)&&p.data.length){data=p.data;state={...state,...p.state};logs=p.logs||[];rebuild();enable(true);$('search').value=state.keyword||'';$('filter').value=state.filter||'all';$('moreFilter').value=state.moreFilter||'';$('sort').value=state.sort||'index';$('operator').value=state.operator||'';$('warehouse').value=state.warehouse||'';render();setStatus('已恢复自动保存的盘点进度。','ok');setSave('','已恢复')}}catch(e){console.error(e);setStatus('无法读取本地自动保存数据。','warn')}})()
